name: Nuget publish

on:
  push:
    branches: master
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: docker://mcr.microsoft.com/dotnet/sdk:6.0-alpine
    steps:
   
    - uses: actions/checkout@v1
    - name: build and publish
      run: |
            dotnet restore
            dotnet pack --output nupkg
            dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API }} -s https://api.nuget.org/v3/index.json
